---

# tshark_bin: /home/se/Documents/programming/git/wiresharek/build/run/tshark

# pyshark_debug: true

docker_hosts:
  default: "unix:///var/run/docker.sock"
  remote_server: "ssh://faui7s4.informatik.uni-erlangen.de"
  remote_client: "ssh://starlink:22005"
  starlink_client: "ssh://starlink:22005"
  astra_client: "ssh://astra:22002"
  eutelsat_client: "ssh://eutelsat:22004"

...
